.SILENT: run

run:
	python predict.py

# virtualenv --system-site-packages -p python3 ./venv
# source ./venv/bin/activate
# pip install --upgrade pip
# pip install --upgrade tensorflow numpy scipy matplotlib ipython jupyter pandas sympy nose opencv-python
